
document.addEventListener('DOMContentLoaded',async()=>{
 let data={};try{data=await fetch('content.json',{cache:'no-store'}).then(r=>r.json())}catch(e){console.error(e)}
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const key='sv-saved-content-v1',read=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}},write=x=>{localStorage.setItem(key,JSON.stringify(x));update()};
 const save=item=>{const a=read(),i=a.findIndex(x=>x.title===item.title);if(i>=0)a.splice(i,1);else a.push(item);write(a)};
 const drawer=document.querySelector('[data-saved-drawer]'),list=document.querySelector('[data-saved-list]'),count=document.querySelector('[data-saved-count]');
 function update(){const a=read();if(count)count.textContent=a.length;document.querySelectorAll('[data-save-title]').forEach(b=>{const on=a.some(x=>x.title===b.dataset.saveTitle);b.classList.toggle('saved',on);b.textContent=on?'Saved':'Save'});if(list)list.innerHTML=a.length?a.map((x,i)=>`<article class="saved-item"><img src="${esc(x.image||'sv-eye.png')}" alt=""><div><span>${esc(x.category||'Content')}</span><h3>${esc(x.title)}</h3></div><button data-remove="${i}">×</button></article>`).join(''):'<div class="saved-empty">Nothing saved yet.</div>';list?.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const a=read();a.splice(+b.dataset.remove,1);write(a)})}
 document.querySelector('[data-open-saved]')?.addEventListener('click',()=>drawer?.classList.add('open'));document.querySelector('[data-close-saved]')?.addEventListener('click',()=>drawer?.classList.remove('open'));
 setTimeout(()=>{document.querySelectorAll('.content-card,.editorial-card,.article-card').forEach(card=>{if(card.querySelector('.card-tools'))return;const title=card.querySelector('h3')?.textContent?.trim();if(!title)return;const image=card.querySelector('img')?.getAttribute('src')||'sv-eye.png';const tools=document.createElement('div');tools.className='card-tools';tools.innerHTML=`<button class="save-button" data-save-title="${esc(title)}">Save</button><button class="share-button">Share</button>`;tools.querySelector('.save-button').onclick=e=>{e.stopPropagation();save({title,image,category:'Slanted View'})};tools.querySelector('.share-button').onclick=async e=>{e.stopPropagation();try{if(navigator.share)await navigator.share({title,text:title,url:location.href});else await navigator.clipboard.writeText(location.href)}catch{}};card.appendChild(tools)});update()},700);
 const input=document.querySelector('[data-discovery-input]'),results=document.querySelector('[data-packet6-results]');function run(q){if(!results)return;const n=q.trim().toLowerCase();if(!n){results.classList.remove('open');return}const m=(data.searchIndex||[]).filter(x=>[x.title,x.description,x.category,x.type].join(' ').toLowerCase().includes(n)).slice(0,8);results.innerHTML=m.length?m.map(x=>`<a class="packet6-result" href="${esc(x.url||'#')}"><img src="${esc(x.image||'sv-eye.png')}" alt=""><div><span>${esc(x.category)}</span><h3>${esc(x.title)}</h3></div><em>${esc(x.type)}</em></a>`).join(''):'<div class="saved-empty">No matches found.</div>';results.classList.add('open')}input?.addEventListener('input',()=>run(input.value));document.querySelectorAll('[data-trend-query]').forEach(b=>b.onclick=()=>{input.value=b.dataset.trendQuery;run(input.value)});
 const pg=document.querySelector('[data-profile-directory]');if(pg)pg.innerHTML=(data.creatorProfiles||[]).map(p=>`<article class="profile-card"><div class="profile-avatar">${esc(p.initials)}</div><span class="profile-role">${esc(p.role)}</span><h2>${esc(p.name)}</h2><p>${esc(p.bio)}</p><div class="profile-tags">${p.focus.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="profile-stats"><div><strong>${esc(p.followers)}</strong><span>Audience</span></div><div><strong>${esc(p.topViews)}</strong><span>Reach</span></div><div><strong>${esc(p.cadence)}</strong><span>Cadence</span></div></div><a class="button button-outline button-small" href="creator.html?slug=${encodeURIComponent(p.slug)}">View Profile</a></article>`).join('');
 const tg=document.querySelector('[data-topic-directory]');if(tg)tg.innerHTML=(data.topicDirectory||[]).map(t=>`<a class="topic-directory-card" href="topics.html?topic=${encodeURIComponent(t.slug)}"><span class="eyebrow">${t.count} pieces</span><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p><span class="view-all">Explore →</span></a>`).join('');
 const host=document.querySelector('[data-creator-profile]');if(host){const s=new URLSearchParams(location.search).get('slug')||'jj',p=(data.creatorProfiles||[]).find(x=>x.slug===s)||data.creatorProfiles?.[0];if(p)host.innerHTML=`<article class="profile-card"><div class="profile-avatar">${esc(p.initials)}</div><span class="profile-role">${esc(p.role)}</span><h1>${esc(p.name)}</h1><p>${esc(p.bio)}</p><div class="profile-tags">${p.focus.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="profile-stats"><div><strong>${esc(p.followers)}</strong><span>Audience</span></div><div><strong>${esc(p.topViews)}</strong><span>Reach</span></div><div><strong>${esc(p.cadence)}</strong><span>Cadence</span></div></div></article>`}
 document.querySelector('[data-inquiry-form]')?.addEventListener('submit',e=>{e.preventDefault();document.querySelector('[data-inquiry-status]').textContent='Inquiry prepared. Connect this form to your CRM before launch.'});update()
});
